import exam1 from '@/exams/exam1'
import exam2 from '@/exams/exam2'
import exam3 from '@/exams/exam3'
import exam4 from '@/exams/exam4'
import exam5 from '@/exams/exam5'
import exam6 from '@/exams/exam6'
import exam7 from '@/exams/exam7'
import exam8 from '@/exams/exam8'
import exam9 from '@/exams/exam9'
import exam10 from '@/exams/exam10'
import exam11 from '@/exams/exam11'
import exam12 from '@/exams/exam12'
import exam13 from '@/exams/exam13'
import exam14 from '@/exams/exam14'

export default [exam1, exam2, exam3, exam4, exam5, exam6, exam7, exam8, exam9, exam10, exam11, exam12, exam13, exam14]
